### ISSUE TITLE
Zergpool changing server format

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1480] opened 2018-03-19 13:01 UTC
See below.  It appears they will now have algo in front of server name.

x11 algo stratum will be working on x11.mine.zergpool.com. We will also change to <ALGO>.mine.zergpool.com:<PORT> server name format, so you can start updating your configuration to support this slowly

**Comment by UselessGuru** [comment] 2018-03-19 15:37
Duplicate of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1478

BTW: github has a search function :-)

**Closed by UselessGuru** 2018-03-19 15:37 UTC
Labels: duplicate
