### ISSUE TITLE
CPU Benchmarking Failing

### ISSUE THREAD

**Issue by pr1me** [MultiPoolMiner/MultiPoolMiner#1106] opened 2018-01-24 19:26 UTC
I'm having an issue on the latest version where it appears to be unable to benchmark any of the CPU algos except for CryptoNight - Even after valid shares sent.

It seems to just ignore the benchmark result and sets the results to 0 inside the stats file. Wondering it this is related to how it grabs the results inside the shell window?

Tried various things like -interval 180 and still the same result, it closes the process and sets the result to 0 inside the benchmark window after successful shares.

CPU being benchmarked is an I7-4770k with 8 gigs of memory

**Comment by UselessGuru** [comment] 2018-01-24 20:57
> Wondering it this is related to how it grabs the results inside the shell window?

There has been no change lately in that area. Each miner belongs to a miner API class (e.g. Ccminer, Prospector etc.) which each use a different API to retrieve hash rate.

Make sure you are only running one instance of MPM.

**Comment by grantemsley** [comment] 2018-01-24 21:31
Post log files please.

**Comment by pr1me** [comment] 2018-01-25 00:41
Thanks for the feedback

This is what I'm seeing in the logs quite a lot, using git version https://github.com/MultiPoolMiner/MultiPoolMiner/commit/643701e5ecdd81ca7dbd30ee678e29f6bbbcc9ee :

> INFO: Selecting best pool for each algorithm...
> INFO: Getting miner information...
> PS>TerminatingError(Invoke-Expression): "The term '-api' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --remoteaccess -S $($Pools.CryptoNight.Host):$($Pools.CryptoNight.Por ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --remoteaccess -S $($Pools.CryptoNight.Host):$($Pools.CryptoNight.Por ...
> +   ~~~~~~~~~~~~
> Unexpected token 'remoteaccess' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --telemetry --server $(if ($Pools.Equihash.SSL) {'ssl://'})$($Pools.E ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --telemetry --server $(if ($Pools.Equihash.SSL) {'ssl://'})$($Pools.E ...
> +   ~~~~~~~~~
> Unexpected token 'telemetry' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "The term '-S' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-S' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 23333 -S $($Pools.Ethash.Host):$($Pools.Ethash.Port) -O $( ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 23333 -S $($Pools.Ethash.Host):$($Pools.Ethash.Port) -O $( ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 13333 -S $($Pools.Ethash2gb.Host):$($Pools.Ethash2gb.Port) ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 13333 -S $($Pools.Ethash2gb.Host):$($Pools.Ethash2gb.Port) ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 23333 -S $($Pools.Ethash.Host):$($Pools.Ethash.Port) -O $( ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 23333 -S $($Pools.Ethash.Host):$($Pools.Ethash.Port) -O $( ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 23333 -S $($Pools.Ethash2gb.Host):$($Pools.Ethash2gb.Port) ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 23333 -S $($Pools.Ethash2gb.Host):$($Pools.Ethash2gb.Port) ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --eexit 1 --api --server $($Pools.Equihash.Host) --port $($Pools.Equi ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --eexit 1 --api --server $($Pools.Equihash.Host) --port $($Pools.Equi ...
> +   ~~~~~
> Unexpected token 'eexit' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:16
> + $env:SystemRoot\System32\msvcr120.dll
> +                ~~~~~~~~~~~~~~~~~~~~~~
> Unexpected token '\System32\msvcr120.dll' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --exitsick -o $($Pools.Lyra2RE2.Protocol)://$($Pools.Lyra2RE2.Host):$ ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --exitsick -o $($Pools.Lyra2RE2.Protocol)://$($Pools.Lyra2RE2.Host):$ ...
> +   ~~~~~~~~
> Unexpected token 'exitsick' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 14028 --api-listen --neoscrypt -o stratum+tcp://$($Pools.N ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 14028 --api-listen --neoscrypt -o stratum+tcp://$($Pools.N ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 24028 --api-listen --neoscrypt -o stratum+tcp://$($Pools.N ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 24028 --api-listen --neoscrypt -o stratum+tcp://$($Pools.N ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "The term '-o' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "The term '-o' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 3336 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$( ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 3336 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$( ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 3334 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$( ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 3334 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$( ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."
> PS>TerminatingError(Invoke-Expression): "At line:1 char:3
> + --api-port 3335 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$( ...
> +   ~
> Missing expression after unary operator '--'.
> 
> At line:1 char:3
> + --api-port 3335 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$( ...
> +   ~~~~~~~~
> Unexpected token 'api-port' in expression or statement."

Hopefully that helps

**Comment by grantemsley** [comment] 2018-01-25 00:45
That is quite helpful. Were you using any previous git versions and did they work properly?

**Comment by pr1me** [comment] 2018-01-25 01:27
Think it was working fine a while back, maybe 2+ weeks or so.
But I really can't remember exactly when, sorry.

**Comment by grantemsley** [comment] 2018-01-25 01:59
It looks like it's trying to run some of the text files as powershell code...which it shouldn't do.  I'm guessing some of your files are corrupt.  The current master version is working fine for me.

Download a fresh copy and see if you get the same errors.

**Comment by UselessGuru** [comment] 2018-01-25 05:59
> It looks like it's trying to run some of the text files as powershell code...which it shouldn't do. I'm guessing some of your files are corrupt

These errors are caused by Aarons change in Get-ChildItemContent. The 'try' is causing it:

    function Invoke-ExpressionRecursive ($Expression) {
        if ($Expression -is [String]) {
            if ((Invoke-Expression "`"$Expression`"") -ne $Expression) {
                try {$Expression = Invoke-Expression $Expression}
                catch {$Expression = Invoke-Expression "`"$Expression`""}
            }
        }

I have not found a way to suppress these errors yet. It's ugly and confusing to read in the log, but there must be another reason.

**Comment by embalmed** [comment] 2018-01-29 19:26
oops guess #1136 is dupe of this

**Comment by UselessGuru** [comment] 2018-02-08 17:03
During testing the newest CpuJayDDee miner 3.8.1 I discovered that this miner takes a very long time until it reports valid hash rates (until it finds a valid share). This will be most likely longer than the default watchdog of 3x 60 seconds and wiil disable the miner with a 0 hash rate file.
Workaround: Use a very long watchdog interval or manually edit the benchmark file manually.

**Closed** 2018-03-10 19:35 UTC
Labels: wontfix, workaround
