### ISSUE TITLE
Dev fee for Xmr-stak (FireiceNvidia.ps1) incorrect

### ISSUE THREAD

**Issue by thebeerbaron2018** [MultiPoolMiner/MultiPoolMiner#2073] opened 2018-08-07 12:40 UTC
I have been looking at the fees associated with the miners and some seem to be incorrect.  For example xmr-stak (FireiceNvidia.ps1) Nvidia is showing as 0.00% fee - but when the miner runs it clearly states 2% fee.  Is this intentional or does the ps1 file need a "fee" line added to the custom object?

**Comment by UselessGuru** [comment] 2018-08-07 13:42
@thebeerbaron2018 

Thank you for pointing it out.
The fee information is currently purely informational - it is not used in any calculations for now.
So the issue is cosmetic, but still confusing.

I'll create a PR to fix it.

**Comment by nemosminer** [comment] 2018-10-12 19:46
xmr-stak (FireiceNvidia) if you compile it yourself it can have a 0% fee i have done this in the past

**Comment by UselessGuru** [comment] 2018-11-26 10:59
Will be fixed in the upcoming 3.2.0 version.

**Closed by UselessGuru** 2018-11-26 10:59 UTC
