### ISSUE TITLE
Pool Prices Issue

### ISSUE THREAD

**Issue by Kettoch** [MultiPoolMiner/MultiPoolMiner#2090] opened 2018-08-18 23:28 UTC
I have been bothered by the pool price bug where it just made a change on the following line.

`        Write-Log -Level Warn "Pool prices are out of sync ($([Int]($Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name |  ForEach-Object {$Pools.$_} | Measure-Object Updated -Minimum -Maximum | ForEach-Object {$_.Maximum - $_.Minimum} | Select-Object -ExpandProperty TotalMinutes)) minutes). "
`
`        Write-Log -Level Warn "Pool prices are out of sync ($([Int]($Pools | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | where {$_.Name -ne "MinungPoolHubCoins"} | ForEach-Object {$Pools.$_} | Measure-Object Updated -Minimum -Maximum | ForEach-Object {$_.Maximum - $_.Minimum} | Select-Object -ExpandProperty TotalMinutes)) minutes). "
`

It seems to have fixed this.  I am watching this but is this works, I suggest a property added to each pool whether it should be checked for pool prices or not.  Especially for dual personality pools like MPH.

I am still observing this but I think this might actually do it.  Because I do not believe for this line MPHC is a working choice.

**Comment by Kettoch** [comment] 2018-08-18 23:31
Well, I haven't quite got it right, but I am still trying.  This sort of bugs me.

**Comment by Kettoch** [comment] 2018-08-18 23:45
Ok, I would like to find a way to put this bug to bed because it seems silly that I get a message after about a week that it is over 8000 minutes out of sync.  I see the relevant section of code but those one-liners are a thing of beauty and hard to crack with out some knowledge of the intent.
Or a serious amount of caffeine while examining it.

**Comment by Byrd1083** [comment] 2018-08-23 15:10
I get this same issue saying pool prices are out of sync. It is so annoying. I hope there is a fix for this soon.

**Comment by UselessGuru** [comment] 2018-08-24 07:31
There is no fix needed :-)

The issue that you are seeing is always caused by the data supplied by the pool.
For each pool MPM keeps an accumulated list of all algorithms you can mine and the pricing information.

Lets say you are using 5 pools:

on first run MPM contacs the 5 pools and receives 20 items per pool (just to keep things simple).
MPM will now have an internal list with 100 (5 x 20) available pools, each has a current time stamp.
You can display this collection with http://localhost:3999/allpools

On the next run MPM contacts all the pools again and receives the same 20 items again. MPM will update the prices and time stamps for all 100 pools.

On one of the subsequent runs one of the pools adds 5 new algorithms and sends 25 (20 + 5new) items.
MPM will now have 105 available pools to mine, all with current time stamps

Now we come to the crucial thing:

on one of the next runs one pool only lists 10 instead of 20 items.
MPM can update the timestamp only on 95 pools, 10 pools keep the old timestamp -> prices are out of sync.
They stay out of sync until the pool is re-sending the missing 10 items, or until you restart MPM.
Its important to understand that the pools constantly update the data available through their API. This is beyond MPMs control.

**Closed by UselessGuru** 2018-08-24 07:31 UTC
