### ISSUE TITLE
WARNING: Pool prices are out of sync (865 minutes). V2.7.2.6

### ISSUE THREAD

**Issue by m-bosch** [MultiPoolMiner/MultiPoolMiner#1349] opened 2018-03-01 12:06 UTC
Hi All,

got it in previous versions also but thought it was an issue with that version. Now on the latest version I get it also.

the pools I use are miningpoolhub and nice hash.

what kind of logs do you need?

**Comment by boro2000** [comment] 2018-03-01 13:23
I submitted a patch: https://github.com/boro2000/MultiPoolMiner/commit/eeb1e3ad104ce26d92ec0ff420923c3a9ff29ddc
Try this :)

**Comment by UselessGuru** [comment] 2018-03-01 16:48
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1351

**Comment by borzaka** [comment] 2018-03-01 16:51
I had the same issue, and I think I know what cousing it: Pool prices are out of sync when they are not included in the Start.bat

For example: I have deleted all the pool files except ahashpool, and started the Start-MiningPoolHub.bat
It's mining to ahashpool, but never updates the pool prices.

**Comment by m-bosch** [comment] 2018-03-01 16:57
Hi @boro2000 don't know it if causes other problems, but the warning is gone indeed.

**Comment by m-bosch** [comment] 2018-03-01 17:08
hi @boro2000 @UselessGuru  to bad, I changed the files en restarted MPM but the warning is still there.

**Comment by UselessGuru** [comment] 2018-03-01 21:18
The warning is cause by include.psm1 line 100:
`if ($ChangeDetection -and [Decimal]$Value -eq [Decimal]$Stat.Live) {$Updated = $Stat.updated}`

For some algorithms, e.g sha256 the pricing information provided by the pool has been unchanged for along time. So on each loop when MPM updates the stat file it compares the current price with the price stores in the stat file. For sha in this case it remained unchanged -> stat update timestamp will not get updated (even though that new pricing information has been received)

**Comment by kiLLeen** [comment] 2018-03-02 04:05
This is a duplicate of #1325

**Comment by aaronsace** [comment] 2018-03-02 11:32
@UselessGuru Why would you select SHA256? Values changing is the only way to detect if the data is not old (i.e. upto 30 minutes in MiningPoolHub's case).

**Comment by UselessGuru** [comment] 2018-03-02 11:43
> Why would you select SHA256? 

I would not, it is an available algo in the NiceHash algo and therefor gets processed.
The price info has not changed @ NH for some days for that algo -> pool prices are old, BUT NOT out of sync

**Comment by aaronsace** [comment] 2018-03-02 11:46
@UselessGuru The algorithms are filtered out, if they are not then that is a bug.

**Comment by UselessGuru** [comment] 2018-03-02 11:55
@aaronsace 
I did my tests with the default parameters from start.bat. There is no excluded algos.

Filtering algos is not the solution anyway. We must keep the stat timestamp updated.

**Comment by borzaka** [comment] 2018-03-02 11:57
I'am having many out of sync warnings as well:
`WARNING: Pool prices are out of sync (143 minutes).`

[MultiPoolMiner_2018-03-02_01-32-34.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1774939/MultiPoolMiner_2018-03-02_01-32-34.txt)

**Comment by aaronsace** [comment] 2018-03-02 22:14
There needs to be timestamps on when the data retrieved from the server actually changes. To fix this issue, the latest timestamp for all the algorithms from within the same pool is used.

**Comment by UselessGuru** [comment] 2018-03-03 00:17
Two cases that cause these warnings:

In an previous run the pool API reported pricing information for an algo. -> stat file created
On subsequent runs:
a) API reports 0 hashrate -> no stat file update ([filtered by pool file](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/957))
b) API reports no price change -> no stat timestamp update

Proposed handling
case a): disable stat file (needs extra flag on stat file), when pricing comes back: enable stat file
case b):  stat timestamp update

Idea:
Add an extra flag (enabled/disabled) to all stat files. This can also be used to selectively enable/disable a specific pool/miner/algo ([e.g. via GUI as I proposed here](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/958))

**Comment by aaronsace** [comment] 2018-03-03 01:19
@UselessGuru Think that's a bit off topic, there is no changes needed to any stat files. The only thing required for this bug to be fixed is to be using the correct timestamp which the core code already has access to.

**Comment by alucard20724** [comment] 2018-03-03 19:55
this seems to be a critical bug and should be fixed/repaired with top priority.  I see this problem more prevalent with my systems that are nvidia gpu.  I have 6 nvidia gpu systems that seem to just sit on the most profitable algo when system is initially started (or profit reset to zero).  I'm just running nicehash, ahashpool, and miningpoolhub pools on those systems.   I've even tried putting the -switchprevention flag to zero in hopes of it changing to the most profitable algo, but it just sticks on the most profitable algo when initially started.

**Comment by aaronsace** [comment] 2018-03-04 00:26
@alucard20724 AHashPool has yet to increase the Keccak precision so the price never changes. 

Try this new fix: b66b2362f5519ba5dbe5021e933d12b39882902e

**Comment by alucard20724** [comment] 2018-03-04 02:08
@aaronsace Just tried it.  I downloaded from the master (dated 03032018 with your new fixes) and it appears to be working now.  I'll start incorporating this into the rest of my machines.  thanks.

**Comment by jeetbarman** [comment] 2018-03-05 13:07
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/b66b2362f5519ba5dbe5021e933d12b39882902e It did resolved selecting most profitable algo.

**Comment by toony63** [comment] 2018-03-06 23:49
hello all
i have the same but the patch dont resolve the problem

2018-03-07 00:47:37 INFO: Selecting best pool for each algorithm.
2018-03-07 00:47:38 WARNING: Pool prices are out of sync (10148 minutes).
2018-03-07 00:47:38 INFO: Getting miner information.

**Closed** 2018-03-15 22:25 UTC
Labels: fixed
