### ISSUE TITLE
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null. master release 6/12/2018 download

### ISSUE THREAD

**Issue by amolitor** [MultiPoolMiner/MultiPoolMiner#1848] opened 2018-06-12 20:27 UTC
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\miners\MultiPoolMiner-master-new\MultiPoolMiner.ps1:532 char:129
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty DeviceNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

**Comment by UselessGuru** [comment] 2018-06-12 20:31
Duplicate of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1828

**Closed by UselessGuru** 2018-06-12 20:31 UTC
