### ISSUE TITLE
The ZPool API is missing

### ISSUE THREAD

**Issue by mkirov0** [MultiPoolMiner/MultiPoolMiner#1296] opened 2018-02-23 11:19 UTC
Idk if its intentional and its a non issue just wanted to put it out there FYI

**Comment by mkirov0** [comment] 2018-02-23 11:34
Could have been more clear couldn't I... 
In the MPM/APIs folder there are .ps1(s) with APIs. The .ps1 for ZPool is missing.
<img width="303" alt="screen shot 2018-02-23 at 1 34 08 pm" src="https://user-images.githubusercontent.com/28104701/36592407-49fd4e42-189e-11e8-84c0-ce6009eec29a.png">

**Comment by UselessGuru** [comment] 2018-02-23 11:48
Files in API folder are required for the different Miners, not pools. So no file is missing.

In your case Zpool is having issues with its web API (unfortunately this happes quite often) - nothing that MPM can change.

**Comment by mkirov0** [comment] 2018-02-23 11:50
Thanks!

**Comment by tbergeron** [comment] 2018-02-23 15:22
If you have too much issues with ZPool I'd suggest augmenting the timeout here: https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/Zpool.ps1#L16-L17 put 30 or 60 seconds instead and the request (zpool api update request) will fails quite less. It fixed most of the timeouts I had with ZPool.

**Comment by mkirov0** [comment] 2018-02-23 22:20
This helps a lot! 
Thank you!

**Comment by mkirov0** [comment] 2018-02-23 22:21
Also I have problems with Excavator... It will just not run... Should I open a new one or continue here?

**Comment by UselessGuru** [comment] 2018-02-24 07:35
> It will just not run... Should I open a new one or continue here?

This seems to be a duplicate of this:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1294
Please continue in that thread.

**Comment by mkirov0** [comment] 2018-02-24 09:12
You guys are awesome! Thanks for all the help!

**Closed** 2018-02-24 12:13 UTC
