### ISSUE TITLE
Suggestion: please allow Mining windows to open normally or minimized

### ISSUE THREAD

**Issue by JimKnightster** [MultiPoolMiner/MultiPoolMiner#1431] opened 2018-03-10 05:12 UTC
I like to check them on occasion to help tune them.  In previous versions you could change the windowstyle to normal, or leave it at minimized.  Now that control is gone and you cant tune miners like claymore using the live tuning ability built into the miner.

Maybe add a command line switch or just change it back to the way it was before?

**Comment by UselessGuru** [comment] 2018-03-10 07:46
Duplicate of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1293

**Closed by UselessGuru** 2018-03-10 07:46 UTC
Labels: duplicate
