### ISSUE TITLE
Write-Log -Level Error "No wallet or username specified. Cannot continue. "

### ISSUE THREAD

**Issue by AlinCG** [MultiPoolMiner/MultiPoolMiner#2092] opened 2018-08-22 16:47 UTC
I am getting this error verry often, like every 1-2 minutes. Can somebody help? Thx.
![untitled](https://user-images.githubusercontent.com/10117503/44477751-36ab8f00-a644-11e8-882d-1b790cd36a56.png)

**Comment by UselessGuru** [comment] 2018-08-22 16:53
You need this: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2081

**Comment by AlinCG** [comment] 2018-08-22 18:56
@UselessGuru  thank you but after i copied the FullyMerged MultiPoolMiner i get no Wallet os UserName configured even if i have them.

![untitled1](https://user-images.githubusercontent.com/10117503/44484332-30bea980-a656-11e8-8e66-171e52dc327a.jpg)

**Comment by AlinCG** [comment] 2018-08-22 21:03
I have tried to configure only per Config.txt and i get the same error. I even tried for both Config.txt and Star.bat and the same error.   To get it to work i am using the MultiPoolMiner.ps1  from https://github.com/MultiPoolMiner/MultiPoolMiner/archive/master.zip    With the file from this zip everything work just fine.  Thanks.

**Comment by UselessGuru** [comment] 2018-08-23 05:16
@AlinCG 

Would you mind posting the problematic start.bat and config.txt? Thank you!

**Comment by skovesh** [comment] 2018-08-25 05:01
That is the exactly problem I had, watch previous issue !

**Comment by UselessGuru** [comment] 2018-08-25 06:57
@skovesh 

We cannot reproduce it... Please upload your start batch file, the config file and the content of the logs folder (zip it together).

**Comment by skovesh** [comment] 2018-08-25 08:14
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Just did it in the previous message. Fact is that another user got the same identical fault!                                                                                                                                                                         Inviato tramite BlackBerry Hub per Android                                                                                                                                                                           Da: notifications@github.comInviato: 25 agosto 2018 09:57A: MultiPoolMiner@noreply.github.comRispondi a: reply@reply.github.comCc: marcello.segal@gmail.com; mention@noreply.github.comOggetto: Re: [MultiPoolMiner/MultiPoolMiner] MultiPoolMiner.ps1:346 char:96 Error (#2092)  @skovesh
We cannot reproduce it... Please upload your start batch file, the config file and the content of the logs folder (zip it together).

**Comment by UselessGuru** [comment] 2018-08-25 09:51
@skovesh 

> Just did it in the previous message.          

You did not supply the contents of the 'Logs' directory. 

> Fact is that another user got the same identical fault!               

I know that there is a problem with some configurations, but as long as I cannot reproduce it I need your assistance. Thank you for your understanding.

**Comment by UselessGuru** [comment] 2018-08-25 10:07
Could you please see if this fixes it:

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094/files#diff-69b5e62237d5f951ca1ac096869d0234

**Comment by skovesh** [comment] 2018-08-25 15:11
last multipoolminer.ps1 from mkirov0 in pool requests already fixed it !
Thanks !

**Comment by UselessGuru** [comment] 2018-08-26 07:08
> last multipoolminer.ps1 from mkirov0 in pool requests already fixed it 

I don't understand. What file?
Please post the link or upload the file.

**Comment by UselessGuru** [comment] 2018-08-27 16:39
@skovesh 

> last multipoolminer.ps1 from mkirov0 in pool requests already fixed it

Could you please post the link or upload the file.

**Comment by UselessGuru** [comment] 2018-08-28 20:00
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094

**Closed by UselessGuru** 2018-08-28 20:00 UTC
