### ISSUE TITLE
Make Excavator reporting the real hashrate faster

### ISSUE THREAD

**Issue by borzaka** [MultiPoolMiner/MultiPoolMiner#1173] opened 2018-02-04 13:48 UTC
## The problem
- It needs approx. 10 minutes to stabilize the hashrate.
- 1 minute is not enough to reach some algorithms maximum hashrate during benchmarks. #971
- It reacts very slowly to realtime overclocks as well. Again I have to wait about 10 minutes to see my overclock results.

## The solution
Use [worker.reset](https://github.com/nicehash/excavator/tree/master/api#worker-reset) 10 seconds after `workers.add`
> When you start workers, the speed is initially zero, then in a short period of time it increases to the maximum. But the initial zero spoils the picture in the arithmetic mean speed. Zero is leveled with time. Here, of course, the question is to the developers and metatology of speed calculation.
> worker.reset starts counting the average speed again, which allows almost instantly see the real speed

[source](https://github.com/nicehash/excavator/issues/170#issuecomment-362839918)

It would look like this in my 6 GPU rig:
```
{
	"time": 13,
	"commands": [
		{"id":1,"method":"worker.reset","params":["0"]},
		{"id":1,"method":"worker.reset","params":["1"]},
		{"id":1,"method":"worker.reset","params":["2"]},
		{"id":1,"method":"worker.reset","params":["3"]},
		{"id":1,"method":"worker.reset","params":["4"]},
		{"id":1,"method":"worker.reset","params":["5"]}
	]
}
```
And probably this is what has to be add to the following miner config files: [ExcavatorNvidia1.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/ExcavatorNvidia1.ps1), [ExcavatorNvidia2.ps1](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/ExcavatorNvidia2.ps1)

```
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("0") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("1") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("2") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("3") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("4") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("5") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("6") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("7") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("8") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("9") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("10") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("11") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("12") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("13") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("14") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("15") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("16") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("17") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("18") + $Commands.$_}) * $Threads},
[PSCustomObject]@{time = 13; commands = @([PSCustomObject]@{id = 1; method = "worker.reset"; params = @("19") + $Commands.$_}) * $Threads},
```

Unfortunately this doesn't help the realtime overclock issue. Because when the overclock settings are changed, the `worker.reset` should be called again. But that's OK, it's outside MPM's scope.

**Comment by UselessGuru** [comment] 2018-07-16 18:07
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1993

BTW: Excavator 1.5.8a does this by design :-)

**Closed by UselessGuru** 2018-07-16 18:07 UTC
