### ISSUE TITLE
Monitoring rejected shares

### ISSUE THREAD

**Issue by conscript91** [MultiPoolMiner/MultiPoolMiner#1457] opened 2018-03-14 16:08 UTC
Is there a way to look for rejected shares, since miners are not popping out in the last few versions.

**Comment by UselessGuru** [comment] 2018-03-14 16:56
Duplicate of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/791

**Closed by UselessGuru** 2018-03-14 16:56 UTC
Labels: duplicate
