### ISSUE TITLE
Something Seems wrong with Keccak algorithm

### ISSUE THREAD

**Issue by robl45** [MultiPoolMiner/MultiPoolMiner#1355] opened 2018-03-01 20:32 UTC
Went and benchmarked everything and the Keccak algorithm was showing insanely high dollar per day.  Like 100 plus dollars a day.   I disabled it for now but I don't know if maybe something is not divided properly?

**Comment by UselessGuru** [comment] 2018-03-01 20:40
> but I don't know if maybe something is not divided properly?

Quite possible :-(
Pools sometimes change the units/divisors they apply to their prices with very short notice. To make 
matters worse the units/divisors are not accessible through the API.

What pool is showing this symptom? Please provide more detailed information.

**Comment by robl45** [comment] 2018-03-01 21:33
It was with Zpool.

**Comment by UselessGuru** [comment] 2018-03-01 21:47
How about some screenshots maybe? How far off was the value?

I don't want to be rude, but when posting here please think like 'What would I need to know so I can help efficiently?' and post accordingly.

**Comment by robl45** [comment] 2018-03-01 22:58
I don't have any screenshots.  Sorry.  It was showing .08 or so btc per day which is like 100 dollars or something when it should be 1 to 3 dollars currently for my rig with 2 1060 and 1 950.  It wasn't jumping up and fluctuating.  It was essentially same amount for an hour or so.

**Comment by mkirov0** [comment] 2018-03-01 23:56
I can confirm the same issue with zpool and earlier (i have no screenshots) with Blockmunch on Keccak as well.
<img width="899" alt="screen shot 2018-03-02 at 1 54 20 am" src="https://user-images.githubusercontent.com/28104701/36876251-b494af66-1dbc-11e8-9995-90b25f80fc2f.png">

**Comment by epiwatson7** [comment] 2018-03-03 01:01
I just wanted to confirm that I had the same issue with Keccak on Zpool.  Algos weren't switching because Keccak was showing like .01 BTC for at least 4 hrs before I finally noticed and excluded it.

**Comment by aaronsace** [comment] 2018-03-03 01:07
@epiwatson7 Yes, @borzaka reported the same issue here #1349 

I've suggested a fix that needs implementing.

**Comment by UselessGuru** [comment] 2018-03-03 22:19
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1359

**Closed by UselessGuru** 2018-03-03 22:19 UTC
