### ISSUE TITLE
logs for i3luefire "ahashpool" problem

### ISSUE THREAD

**Issue by i3luefire** [MultiPoolMiner/MultiPoolMiner#740] opened 2017-12-19 01:39 UTC
[2017-12-17_23-11-22.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570002/2017-12-17_23-11-22.txt)

[2017-12-17_21-47-27.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570004/2017-12-17_21-47-27.txt)
[2017-12-17_21-53-11.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570005/2017-12-17_21-53-11.txt)

**Comment by UselessGuru** [comment] 2017-12-19 06:17
What is your exact problem?
In any case remove the NiceHash pool file - NH ist down.

**Comment by i3luefire** [comment] 2017-12-19 12:06
The problem was that I don't have ahashpool enabled and it was running.

**Comment by UselessGuru** [comment] 2017-12-19 12:42
Why do you think ahashpool was 'running'? MPM just read the pool information, but it never launched a miner against it - excactly as designed.

Please note: not having a specific poolname included in the command line does not mean that MPM will not read pool data from it.
If you absolutely do not want MPM to use any pool information from aparticular pool, then you have to delete the corresponding pool file.

**Comment by i3luefire** [comment] 2017-12-19 13:26
Alright. I thought it was mining with that pool. My fault I see that it didn't actually mine now.

**Comment by i3luefire** [comment] 2017-12-20 12:22
![image](https://user-images.githubusercontent.com/3527233/34206959-1f31579a-e54e-11e7-9eb6-02e8d5255b2b.png)

**Comment by i3luefire** [comment] 2017-12-20 12:23
![image](https://user-images.githubusercontent.com/3527233/34206997-44358796-e54e-11e7-9eb6-845bf3bef347.png)

**Comment by i3luefire** [comment] 2017-12-20 12:23
it is now mining on ahashpool and hash refinery

**Comment by i3luefire** [comment] 2017-12-20 12:26
![image](https://user-images.githubusercontent.com/3527233/34207123-bde077fe-e54e-11e7-9e4b-85d61c25869f.png)

**Comment by i3luefire** [comment] 2017-12-20 12:26
and zpool

**Comment by aaronsace** [comment] 2017-12-20 12:34
@i3luefire Please post the logs.

**Comment by i3luefire** [comment] 2017-12-20 12:39
[2017-12-19_21-53-49.txt](https://github.com/aaronsace/MultiPoolMiner/files/1575529/2017-12-19_21-53-49.txt)
[Uploading 2017-12-20_00-46-37.txt…]()
[Uploading 2017-12-19_21-49-24.txt…]()

**Comment by i3luefire** [comment] 2017-12-20 12:40
[2017-12-20_00-46-37.txt](https://github.com/aaronsace/MultiPoolMiner/files/1575533/2017-12-20_00-46-37.txt)
[2017-12-19_21-49-24.txt](https://github.com/aaronsace/MultiPoolMiner/files/1575534/2017-12-19_21-49-24.txt)
[2017-12-19_21-53-49.txt](https://github.com/aaronsace/MultiPoolMiner/files/1575535/2017-12-19_21-53-49.txt)

**Comment by fonyo** [comment] 2017-12-22 12:31
I see it, it was mining on other pools but only briefly. It could have been due to MPH going down/not responding for a hot minute? So the failover mechanism kicked in.

**Comment by fonyo** [comment] 2017-12-22 12:35
MPH received DDoS attacks recently, it was unavailable sometimes due to the high load. Pool operator also stated he changed cloudflare protection to "strict" which could cause the pool to deny a response to you.

Everything should be back to normal now. Can you confirm?

**Comment by i3fe-at-work** [comment] 2017-12-22 13:24
I went back to using 2.7.1.1 on that machine so I can't confirm what the problem was

**Comment by fonyo** [comment] 2017-12-24 10:02
Should be fixed in the next release.

**Closed by fonyo** 2017-12-24 10:02 UTC
