### ISSUE TITLE
MINING STOPS WITH CPU UTILISATION INCREASE FOR CCMINER

### ISSUE THREAD

**Issue by jeetbarman** [MultiPoolMiner/MultiPoolMiner#1377] opened 2018-03-04 07:01 UTC
It seem for last 5 minute MPM was siting idle with high CPU utilisation due to ccminer-x64 although same was not been used by MPM.

![image](https://user-images.githubusercontent.com/36787233/36942950-debf4ee6-1fa5-11e8-893b-cf17a8f4e133.png)
As per log Bminer was stopped and ccminer start command was initiated which in return spiked CPU utilisation but mining was not happening as MSI afterburner was idle.
![image](https://user-images.githubusercontent.com/36787233/36942960-10d05b96-1fa6-11e8-8254-c8d5289d3fdc.png)
 
![image](https://user-images.githubusercontent.com/36787233/36942966-36b04d94-1fa6-11e8-8072-5d6decc0f4ca.png)

Shouldn't MPM take necessary action once miner stops working (5 minute)?

**Comment by UselessGuru** [comment] 2018-03-04 08:28
Please zip you log directory and upload - TIA.

**Comment by jeetbarman** [comment] 2018-03-04 08:40
[MultiPoolMiner_2018-03-04.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778308/MultiPoolMiner_2018-03-04.txt)

**Comment by jeetbarman** [comment] 2018-03-04 08:46
Here is the entire Log.zip
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778310/Logs.zip)

**Comment by UselessGuru** [comment] 2018-03-05 12:20
Thanks for the logs.
The last miner that got startet was Excavator:
`2018-03-04 13:57:17 INFO: Starting miner (ExcavatorNvidia1): 'C:\MultiPoolMiner-master\Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHub_Lyra2RE2_jeetbarman.GTX1070TI_1_Nvidia.json -na'`

So this might be the same excavator problem as [seen here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1294)

Excavator does not write a log file in the 'logs' directory. Can you see if there are log files (*_log.txt) in the excavator directory 'Bin\Excavator'? I'm interested in log files from  around 2018-03-04 13:57:17

**Comment by jeetbarman** [comment] 2018-03-05 12:28
Sorting by date under "Bin\Excavator" I was unable to find any log, is there any other location from where I can give you log?

Also if you check my initial screenshot issue started  at 2018-03-04 12:05:03 and not 13:57:17 not sure if both are interlink.

![image](https://user-images.githubusercontent.com/36787233/36974876-40324a40-209e-11e8-91bc-ca174919aee5.png)

**Comment by UselessGuru** [comment] 2018-03-05 13:25
@jeetbarman 

There should be files named '*_log.txt' in that folder.
The json files are the actual config file that are passed to excavator (e.g.-c MiningPoolHub_Lyra2RE2_jeetbarman.GTX1070TI_1_Nvidia.json).
On each loop MPM creates new JSON files (in case E becomes the most profitable miner to be executed), so the JSON files will mostly newer than the log files.

> Also if you check my initial screenshot issue started at 2018-03-04 12:05:03 and not 13:57:17 not sure if both are interlink.

Your problem is caused by excavator. It gets started, nothing happens, and after 9 minutes watchdog kicks the miner:

```
2018-03-04 11:51:49 INFO: Starting miner (ExcavatorNvidia2): 'C:\MultiPoolMiner-master\Bin\Excavator\excavator.exe -p 23456 -c MiningPoolHub_NeoScrypt_jeetbarman.GTX1070TI_2_Nvidia.json -na'
2018-03-04 11:51:49 INFO: Pinging monitoring server. 
2018-03-04 11:51:50 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
```
...
```
2018-03-04 12:00:36 INFO: Stopping miner (ExcavatorNvidia2). 
2018-03-04 12:00:36 INFO: Starting miner (BMiner): 'C:\MultiPoolMiner-master\Bin\NVIDIA-BMiner\BMiner.exe -api 127.0.0.1:1880 -uri stratum://jeetbarman.GTX1070TI:x@asia.equihash-hub.miningpoolhub.com:17023 -nofee -watchdog=false'
2018-03-04 12:00:36 INFO: Pinging monitoring server. 
2018-03-04 12:00:37 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
2018-03-04 12:00:39 INFO: Start waiting before next run. 
```

I asked for events for the last excavator start, because the cause is the same.

**Comment by jeetbarman** [comment] 2018-03-05 14:13
@UselessGuru There seem to be no log file for Excavator, any idea why so?

![image](https://user-images.githubusercontent.com/36787233/36979389-5cc09842-20ad-11e8-8585-a8bd41a400c8.png)

**Comment by UselessGuru** [comment] 2018-04-05 10:58
Excavator issues should be resolved with this commit:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/a0857c0757ac2577df7c2631e31d746383d5a442

**Closed by UselessGuru** 2018-04-05 10:58 UTC
