### ISSUE TITLE
AMD miners

### ISSUE THREAD

**Issue by Pandoraaaaa** [MultiPoolMiner/MultiPoolMiner#1736] opened 2018-05-17 08:57 UTC
Hi,

I'm in the process of benchmarking an amd rig. I put all the current algos and pools into start.bat, but I'm not seeing all the miners that serve those algos. Take x16r, for example. Am I missing something obvious or do I need to add the missing miners myself? Do you need a complete list of the algos that do not have miners? - I can work on that. Thanks.

**Comment by Pandoraaaaa** [comment] 2018-05-17 09:17
Here are the algos not listed for benchmarking:
Bitcore,
C11,
X11,
HMQ1725,
HSR,
JHA,
Phi,
Polytimos,
Quark,
Qubit,
Scrypt,
SHA256,
Sib,
Skunk, 
Timetravel,
Tribus,
Veltor,
X11,
X12,
X11evo,
X16R,
X16S,
X17

Please let me know how I should proceed to get these algos benchmarked. Thanks.

**Comment by mkirov0** [comment] 2018-05-17 09:18
Did you just download a fresh copy of MPM?
> do I need to add the missing miners myself

Probably not. What MPM mines mostly depends on what your start.bat contains.
Can you upload logs and the contents of your start.bat?

**Comment by Pandoraaaaa** [comment] 2018-05-17 09:35
Hi, thanks for fast response. Yes, I downloaded the master zip into an empty folder just before I started.

My start.bat contains all the current algos and all the current pools that I copy/pasted in from readme.md:

Bitcore, Blakecoin, Blake2s, BlakeVanilla, C11, CryptoNightV7, Ethash, X11, Decred, Equihash, Groestl, HMQ1725, HSR, JHA, Keccak, Lbry, Lyra2RE2, Lyra2z, MyriadGroestl, NeoScrypt, Pascal, Phi, Polytimos, Quark, Qubit, Scrypt, SHA256, Sib, Skunk, Skein, Timetravel, Tribus, Veltor, X11, X12, X11evo, X16R, X16S, X17, Yescrypt

And here are the pools (I took out Yimp though)
ahashpool, ahashpoolcoins, blazepool, blockmasters, blockmasterscoins, hashrefinery, miningpoolhub, miningpoolhubcoins, nicehash, yiimp, zergpool, zergpoolcoins, zpool, zpoolcoins

Maybe of interest, I also have an nvidia rig is running the same start.bat with nvidia in the type field obviously. Anyway, that machine has all the algos listed for benchmarking, over 100, while the amd list is only 35 members.

I can get the start.bat if you need it, but I'm at my chromebook now. Let me know. I reset logs after every restart, so maybe that won't help so much. Maybe a screen capture of the benchmarked profit table would help?

**Comment by Pandoraaaaa** [comment] 2018-05-17 09:53
Here is start.bat, and I've uploaded a screen capture of the profit table that shows all the candidates
```
@cd /d %~dp0

@if not "%GPU_FORCE_64BIT_PTR%"=="1" (setx GPU_FORCE_64BIT_PTR 1) > nul
@if not "%GPU_MAX_HEAP_SIZE%"=="100" (setx GPU_MAX_HEAP_SIZE 100) > nul
@if not "%GPU_USE_SYNC_OBJECTS%"=="1" (setx GPU_USE_SYNC_OBJECTS 1) > nul
@if not "%GPU_MAX_ALLOC_PERCENT%"=="100" (setx GPU_MAX_ALLOC_PERCENT 100) > nul
@if not "%GPU_SINGLE_ALLOC_PERCENT%"=="100" (setx GPU_SINGLE_ALLOC_PERCENT 100) > nul
@if not "%CUDA_DEVICE_ORDER%"=="PCI_BUS_ID" (setx CUDA_DEVICE_ORDER PCI_BUS_ID) > nul

rem  -disableautoupdate false

@set "command=& .\multipoolminer.ps1 -wallet nnnnnnnnnnnnnnnnnnnnnnnnnnnnn -username nnnnnn -workername nnnnn -region usa -currency usd -type amd -ShowMinerWindow -ExcludeWatchdogAlgorithm x16r -poolname ahashpool,ahashpoolcoins,blazepool,blockmasters,blockmasterscoins,hashrefinery,miningpoolhub,miningpoolhubcoins,nicehash,zergpool,zergpoolcoins,zpool,zpoolcoins -algorithm Bitcore,Blakecoin,Blake2s,BlakeVanilla,C11,CryptoNightV7,Ethash,X11,Decred,Equihash,Groestl,HMQ1725,HSR,JHA,Keccak,Lbry,Lyra2RE2,Lyra2z,MyriadGroestl,NeoScrypt,Pascal,Phi,Polytimos,Quark,Qubit,Scrypt,SHA256,Sib,Skunk,Skein,Timetravel,Tribus,Veltor,X11,X12,X11evo,X16R,X16S,X17,Yescrypt -donate 10 -interval 180 -watchdog -minerstatusurl https://multipoolminer.io/monitor/miner.php -switchingprevention 2"

start pwsh -noexit -executionpolicy bypass -command "& .\reader.ps1 -log 'MultiPoolMiner_\d\d\d\d-\d\d-\d\d\.txt' -sort '^[^_]*_' -quickstart"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/PowerShell-6.0.2-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause

```
![benchmark](https://user-images.githubusercontent.com/31040740/40170421-a474ab22-5985-11e8-8a1f-3f6e776e73e8.jpg)

**Comment by mkirov0** [comment] 2018-05-17 10:00
If you have a running system with the same start.bat it likely it isn't the problem. I dont have an AMD system so I can't test this, but I think AMDs don't mine all the algos NVIDIA does. Reasons can be support and/or profitability. You can take a look at #1733 and see what symalla is mining. Also if you want to you can add miners from #1722 and #1717 if you know what you are doing. I am sure he has tested on his system, but just in case you don't have time to troubleshoot, you can wait until they are merged into the master to make sure they are 100% working.

**Comment by Pandoraaaaa** [comment] 2018-05-17 10:06
Thanks for response. You've stated my concern exactly. I am guessing I will need to add miners for the missing algos (or some subset) manually and I just wanted to confirm that fact. Master repo for nvidia looks very complete!

Anybody that is running amd, if you could please scan that list of missing algos and comment on what is worth chasing down? X16r jumps out immediately...here is the missing algo list again for convenience:

Here are the algos not listed for benchmarking:
Bitcore,
C11,
X11,
HMQ1725,
HSR,
JHA,
Phi,
Polytimos,
Quark,
Qubit,
Scrypt,
SHA256,
Sib,
Skunk,
Timetravel,
Tribus,
Veltor,
X11,
X12,
X11evo,
X16R,
X16S,
X17

**Comment by mkirov0** [comment] 2018-05-17 10:11
What I can say as a non AMD miner is that Quark, Qubit, Scrypt, SHA-256, Sib, X11 and maybe even X12 are not worth the hassle since the are already ASIC-ed.

**Comment by Pandoraaaaa** [comment] 2018-05-17 10:16
Haha, so is eth, but it still comes up the rankings. I'd like to let the MPM algo do the work of deciding. My questions is which amd miners that I should add? I'll probably chase it all down myself anyway, but also happy to get any help I can! :)

**Comment by Pandoraaaaa** [comment] 2018-05-17 10:19
Hey thank you for the response, I didn't mean to come off glib. I will take your comment into account! :)

**Comment by UselessGuru** [comment] 2018-05-17 10:51
To mine an algorithm it must be available at at least one MPM pool. This gives you a list off all currently available algorithms:

http://localhost:3999/algorithms

And then you need a miner that can mine the algo. :

http://localhost:3999/miners

**Comment by Pandoraaaaa** [comment] 2018-05-17 11:47
Thank you for responding! Those links aren't working for me

**Comment by UselessGuru** [comment] 2018-05-17 11:51
The are... but they work only if MPM is running on your machine. 
The retrieve live data from MPM - the are not lings to something on the internet.

**Comment by Pandoraaaaa** [comment] 2018-05-17 12:01
Oh, hahha, I am on chromebook, will check it out, thanks. :)

**Comment by alucard20724** [comment] 2018-05-17 14:46
Not to crap on the thread.  I've brought up the issue about amd months ago to no avail, and it still looks like the the release is at 2.7.2.7.  I've since then switch all my machines to megaminer, which has all the algo that OP listed, and they work for AMD cards (ok... except maybe timetravel).  I've stopped using mpm all together because of this.  I've been monitoring this github thread for updates for months now in hopes of a viable update.

@UselessGuru Get yourself an AMD card, seriously.  the excuse that you don't have an AMD card to test with is getting old.  If you can't test AMD, then you shouldn't be writing the code for AMD.  

Where has @fonyo gone?

**Comment by mkirov0** [comment] 2018-05-17 16:12
@alucard20724 I said I dont have an AMD card not UslessGuru. Just FYI you can push new miners if you have better options, the devs are very reasonable and accept new stuff.

**Comment by Pandoraaaaa** [comment] 2018-05-17 17:15
I'm willing to do some of the ground work on amd, but I will need some help/advice because my mpm skills are only one step above noob at this point. I can work with the blockmasters pool and see about adding algos/miners for that case. Currently have neoscrypt, skein, and lyra2re2 on my amd test rig. For me that's a profitable starting point. Sorry I can't do more on this til tomorrow, I have real coding job. :P

**Comment by UselessGuru** [comment] 2018-05-17 18:45
> Get yourself an AMD card, seriousl

Send me money then I will. Seriously!

**Comment by UselessGuru** [comment] 2018-05-17 18:48
>  can work with the blockmasters pool and see about adding algos/miners for that case.

Any help is appreciated.
It not the pools that need work, it is the miners. The pool files automagically add any algorithm that the pool exposes through its API.
You then need a miner that can mine the algorithms, and that is where MPM 's weak pint is when it comes to AMD.

> I've since then switch all my machines to megaminer

Megaminers miner files should actually also work with MPM... but I've nerver tested.

**Comment by Pandoraaaaa** [comment] 2018-05-17 19:37
Oh man don't feel bad, it is working great for nvidia!

**Comment by Pandoraaaaa** [comment] 2018-05-18 06:40
I like this idea of copying from MegaMiner! An opportunity to give back to parent project, yes?

I need to consider test environment for this task. One question - can I run multiple copies of mpm (or megaminer) out of different folders simultaneously on same rig? One instance for nvidia and one instance for AMD in mixed rig - then I could separate one card (rx 560 4g) for small standalone AMD setup elsewhere for testing.

I will download and benchmark megaminer today so that will be a learning curve. I just started mining last January with MPH + MPM. Maybe @alucard20724 can be helpful - I saw he is active on bitcointalk megaminer thread.

One thing I noticed is that megaminer is not supporting blockmaster so I can do broad range of anonymous pools for benchmarks and proceed from there.

**Comment by UselessGuru** [comment] 2018-05-18 11:48
> can I run multiple copies of mpm (or megaminer) out of different folders simultaneously on same rig

That should work - but is not recommended and untested.

**Comment by Pandoraaaaa** [comment] 2018-05-18 12:29
Ok, I will try it out. I just got this perfect setup with mpm for nvidia right now and I want to let it run. Oh, but I have to move gpu to different machine. I can just copy stats folder to avoid re-benchmarking I believe. Also need startup config.txt and start.bat and miners should then auto download...

**Comment by grantemsley** [comment] 2018-05-18 21:04
@alucard20724 I must have missed your previous thread about it.  I do have one system with an AMD card for testing purposes.  If you can let me know which miners are most profitable in megaminer, I can focus on getting those added first.

**Comment by Pandoraaaaa** [comment] 2018-05-19 03:46
Hi, I plan to run megaminer, but I just got everything stable with mpm and wanted to get a little more actual return data on blockmasters before taking everything apart again. I'm wondering if blockmasters is overestimating profits. Also I have all the parts together to finally to build another rig (also AMD) this weekend so that's a priority.

**Comment by mkirov0** [comment] 2018-05-19 07:48
@Pandoraaaaa Its not just Blockmasters doing the overestimations... I can confirm Ahahshpool estimating almost double the actual 24hr return rata for a few days now...

**Comment by Pandoraaaaa** [comment] 2018-05-19 11:00
Sigh, so lame-o. Thanks for the info. Since we are getting in the spirit of "upstream merging" from megaminer, I'll mention that I saw a fudge factor for adjusting profits. Here are the default values:

@@POOLPROFITFACTOR_AHASHPOOL=0.7
@@POOLPROFITFACTOR_NICEHASH=1
@@POOLPROFITFACTOR_MININGPOOLHUB=0.8
@@POOLPROFITFACTOR_ZPOOL=0.7
@@POOLPROFITFACTOR_ZERGPOOL=0.5
@@POOLPROFITFACTOR_BLAZEPOOL=0.7
@@POOLPROFITFACTOR_BSODPW=0.7
@@POOLPROFITFACTOR_YIIMP=0.7

For my specific case with amd running neoscrypt, skein, and lyra2re2 (mostly neoscrypt) on blockmaster on one rig and a big mix of algos/miners on a single nvidia card rig, I never saw less than $3/day on the screen with spikes to $8 but the 24 hour return was only $2. Very bad.

I thought my new mobo was here but it was just a keyboard/mouse, sweet wireless, but still I have a bunch of cards (rx 560) sitting in a bucket doing nada. And I'm convinced not to waste any more time on blockmaster pool, so maybe I'll get started with the megaminer testing today.

**Comment by mkirov0** [comment] 2018-05-19 14:53
I doubt the redirection part, but can't be certain. I have monitored the has rates reported by the miners/mpm and what show on the pool site and it has always been within a margin of error. At times I have seen very low hash rates but at the same time I have seen double the has rates reported by the miners/mpm, so it averages out at the end.
I was thinking of doing something like (Current Estimate + 24hr Estimate + 24hr Actual) / 3, but when I gave it some more time I came to the conclusion it will dampen the opportunities to get on the Moon Wagon asap... I am guessing the profit factors do the same thing, but it seems too artificial to me. Just my 2 cents.

**Comment by Pandoraaaaa** [comment] 2018-05-19 22:05
Well today was a big fat fail. I even reinstalled windows on a machine with an hdd (not sdd) and no usb 3 either, so that sucked. Bottom line is the tiny mobo I'm using for testing doesn't have enough power for the pcie slot (35W) - prev I was using a card that had one of those extra power plugs direct from the psu to the card. So anyway the RX 560 would not run. I need to reconsider, I do have rx 570 with the aug power maybe I'll try that tomorrow.

**Closed** 2018-06-02 07:01 UTC
