### ISSUE TITLE
Miners not showing on latest clone.

### ISSUE THREAD

**Issue by patq911** [MultiPoolMiner/MultiPoolMiner#1190] opened 2018-02-07 21:00 UTC
I'm relaying this comment from reddit, https://www.reddit.com/r/multipoolminer/comments/7vvdlc/miners_not_showing/

I also have this problem as described.  The miners are running but I can't see them in a window like before.  The last version I was using was the last official release.

**Comment by UselessGuru** [comment] 2018-02-07 22:30
This is by design.

**Comment by aaronsace** [comment] 2018-02-07 22:35
The windows are stored live in the logs folder. 
I may add a monitor window if I get chance.

**Comment by patq911** [comment] 2018-02-08 03:09
I would prefer an option at least, but thanks for letting us know.

**Comment by grantemsley** [comment] 2018-02-08 05:41
Haven't tried the latest version yet, but I plan to add those live logs to the GUI I'm working on.

**Comment by m-bosch** [comment] 2018-02-08 18:40
>I would prefer an option at least, but thanks for letting us know.

@patq911  yes, a monitor window or an option to toggle it would be awesome. It is comforting if you see the miners work ;-)

**Comment by korishan** [comment] 2018-02-09 14:19
I agree. On the build I got from grantemsley, I started noticing some odd behavior. There were several miners loaded at once on the same device.  I mention it here: #1204 
Being able to see which miners are loaded and the ability to do something with them would be nice.

Here's an idea, could you make the main PS script show the active miners and give you the option to close them from there? Such that you select "M" for miner, then select a number of the miner, then "C" to close it.

**Comment by korishan** [comment] 2018-02-09 19:45
Is there a way to turn this off for now? Manually go into a file and remove a setting or change it to something else? I can't find "Hidden" or "WindowStyle" anywhere other than the main startup scripts for the powershell commands.

**Comment by UselessGuru** [comment] 2018-02-10 09:50
> Is there a way to turn this off for now? 

No, this is where development is heading.
If you don't like it then stick with the official release older use an alternate build.

**Comment by VukaKun** [comment] 2018-02-10 17:42
Could someone at least point to the part of the code responsible for this? It's not that obvious, at least to me.

**Comment by adamje42** [comment] 2018-02-10 17:46
@VukaKun 

c768136c5caf893cba9b8a1c02b7f2040186a763

**Comment by VukaKun** [comment] 2018-02-10 17:49
@adamje42 Thanks!

**Comment by UselessGuru** [comment] 2018-02-18 12:32
[Duplicate](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1215)

**Closed by UselessGuru** 2018-02-18 12:32 UTC
Labels: duplicate
