### ISSUE TITLE
Multipoolminer stop working

### ISSUE THREAD

**Issue by sas152ana** [MultiPoolMiner/MultiPoolMiner#1541] opened 2018-04-02 18:20 UTC
Hello, help me please (sorry for my english)
Sometimes multipoolminer just stop mining for endless time. Not long ago it didn't mine for 6 hourses, when i backed home, i restarted it. I make screenshot of another stopping few minuts ago.
I wrote -watchdog in start.bat but it isn't help me there : ) 
![help](https://user-images.githubusercontent.com/38014412/38208934-43e07d5a-36bb-11e8-9ea6-c230741a156c.png)
What can i do to prevent it?

**Comment by UselessGuru** [comment] 2018-04-02 18:25
Duplicate of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1459

**Comment by sas152ana** [comment] 2018-04-02 18:31
Thank you!

**Closed** 2018-04-02 18:35 UTC
Labels: duplicate
