### ISSUE TITLE
sgminer fails when is launched from MPM with algorithm Skein-AMD and Lyra2z-AMD

### ISSUE THREAD

**Issue by scolarita13** [MultiPoolMiner/MultiPoolMiner#1540] opened 2018-04-02 17:29 UTC
Multipool miner indicates the sgminer  fail for two algorithms Skein-AMD and Lyra2z-AMD.
I have executed individually the miner as is displayed by MPM console.
sgminer.exe --api-listen -k lyra2z -o stratum+tcp://lyra2z.mine.zpool.ca:4553 -u 3LnjwBNxDGdFpjdD5rbZMrTV3GVr9LuMKc -p scolaritaMiner,c=BTC --worksize 32 --intensity 18 --gpu-platform 1
sgminer.exe --api-listen -k skeincoin -o stratum+tcp://skein.mine.zpool.ca:4933 -u 3LnjwBNxDGdFpjdD5rbZMrTV3GVr9LuMKc -p scolaritaMiner,c=BTC --gpu-threads 2 --worksize 256 --intensity d --gpu-platform 1
In both cases they runs without any error and submit shares to ZPOOL
They fail only when are launched by MPM.

Any idea why?

Scolaritza

**Comment by scolarita13** [comment] 2018-04-02 17:32
One more thing.
The same miner does not fail for Lyra2RE2, Groestl, and Keccak.

**Comment by UselessGuru** [comment] 2018-04-02 18:06
Duplicate of https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1493???

See this commit: 0957a0a

This should fix it.

**Comment by grantemsley** [comment] 2018-04-02 18:26
@UselessGuru I'm not certain yet, but that commit may not completely fix the issue...I have some of the sgminers working now, but most failing.  Not sure if it's just something wrong with my hardware yet though. I'm looking into it.

**Comment by scolarita13** [comment] 2018-04-02 19:46
I have replaced those fails and the miners still fail. What is interesting when I run the miner individually it does not fail.

**Comment by alucard20724** [comment] 2018-04-03 03:01
i think this is part of the redirection not supported error https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1493

I'm going to try out the mention fix and see if that works.

**Comment by angelics** [comment] 2018-05-11 14:01
check  #1414 and test  #1668

**Closed** 2018-06-22 12:07 UTC
Labels: duplicate
