### ISSUE TITLE
Multipoolminer Freeze

### ISSUE THREAD

**Issue by spartan5v5** [MultiPoolMiner/MultiPoolMiner#1370] opened 2018-03-03 16:40 UTC
Hello, multipoolminer stop mining a freeze, must close and restart miner.

Im mining in zpool only, I deleted all the others pool files and keep zpool pool file.

**Comment by aaronsace** [comment] 2018-03-03 17:25
Please provide screenshots of what you are actually seeing (what is freezing/closing/restarting) and zip up the logs folder then drop onto the GitHub post.

**Comment by spartan5v5** [comment] 2018-03-03 17:32
I have restarted and deleted the logs, ill wait for it.

Other thing, if i put only zpool on .bat file after a while start mining other pools, i have deleted from pools folder and get a lot of red lines but is mining only in zpool.

**Comment by aaronsace** [comment] 2018-03-03 17:37
Cheers, will definitely need logs at a minimum.

**Comment by spartan5v5** [comment] 2018-03-04 06:52
Stop again in this point.

![captura de pantalla](https://user-images.githubusercontent.com/37022773/36942956-3934f900-1f80-11e8-92ae-a68702d2c1b3.jpg)

I put all logs in zip file.

[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778266/Logs.zip)

**Comment by UselessGuru** [comment] 2018-03-04 08:26
I can see two critical issues in the provided logs. Not sure if they are the cause for the hang.

CcminerLyra2z-...: `[2018-03-04 02:00:38][31m Unable to query number of CUDA devices! Is an nVidia driver installed?[0m`
Dstm-...: `nvmlInit failed: Insufficient Permissions`

Install the **full** Nvidia driver again (best to fully uninstall and clean your system with DDU)

**Comment by spartan5v5** [comment] 2018-03-04 08:31
I did clean driver reinstall with DDU, im going to try again.

What about "Dstm-...: nvmlInit failed: Insufficient Permissions"?

**Comment by spartan5v5** [comment] 2018-03-04 10:39
Again with all clean drivers and clean logs.
[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1778384/Logs.zip)

**Comment by UselessGuru** [comment] 2018-03-04 16:35
> What about "Dstm-...: nvmlInit failed: Insufficient Permissions"?

Ask the miner developer. This is a miner ant MPM issue.

**Comment by spartan5v5** [comment] 2018-03-05 06:53
Again stop here... it cant run 24h

![captura de pantalla 2018-03-05 a las 7 49 17](https://user-images.githubusercontent.com/37022773/36961029-cc21433a-2049-11e8-95fc-aa27183b5714.png)


[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1779794/Logs.zip)

**Comment by spartan5v5** [comment] 2018-03-05 13:16
I have only zpool in pools folder.

In event viewer i got this.

2018-03-05 13:30:46 INFO: Starting next run.
2018-03-05 13:30:47 INFO: Updating exchange rates from Coinbase.
2018-03-05 13:30:47 INFO: Loading saved statistics.
2018-03-05 13:30:48 INFO: Loading pool information.

Stop again in loading pool information.

**Comment by UselessGuru** [comment] 2018-03-05 16:31
> I have only zpool in pools folder.

Any subdirectories? bak files?

**Comment by spartan5v5** [comment] 2018-03-05 16:39
only zpool.ps1

**Comment by UselessGuru** [comment] 2018-03-05 18:11
Post your copy of zpool.ps1 (you need to rename is as zpool.txt). I am sure it is broken.

**Comment by aaronsace** [comment] 2018-03-05 18:44
@spartan5v5 I am 99% sure that you have moved all the files that were in the pools folder into a subfolder.

**Comment by spartan5v5** [comment] 2018-03-05 19:27
There is only zpool.ps1 in pools folder, is this: 

using module ..\Include.psm1

param(
    [alias("Wallet")]
    [String]$BTC, 
    [alias("WorkerName")]
    [String]$Worker, 
    [TimeSpan]$StatSpan
)

$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName

$Zpool_Request = [PSCustomObject]@{}

try {
    $Zpool_Request = Invoke-RestMethod "http://www.zpool.ca/api/status" -UseBasicParsing -TimeoutSec 150 -ErrorAction Stop
    $ZpoolCoins_Request = Invoke-RestMethod "http://www.zpool.ca/api/currencies" -UseBasicParsing -TimeoutSec 150 -ErrorAction Stop
}
catch {
    Write-Log -Level Warn "Pool API ($Name) has failed. "
    return
}

if (($Zpool_Request | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Measure-Object Name).Count -le 1) {
    Write-Log -Level Warn "Pool API ($Name) returned nothing. "
    return
}

$Zpool_Regions = "us"
$Zpool_Currencies = @("BTC") + ($ZpoolCoins_Request | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name) | Select-Object -Unique | Where-Object {Get-Variable $_ -ValueOnly -ErrorAction SilentlyContinue}

$Zpool_Request | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | Where-Object {$Zpool_Request.$_.hashrate -gt 0} |ForEach-Object {
    $Zpool_Host = "mine.zpool.ca"
    $Zpool_Port = $Zpool_Request.$_.port
    $Zpool_Algorithm = $Zpool_Request.$_.name
    $Zpool_Algorithm_Norm = Get-Algorithm $Zpool_Algorithm
    $Zpool_Coin = ""

    $Divisor = 1000000

    switch ($Zpool_Algorithm_Norm) {
         "blake2s" {$Divisor *= 1000}
        "blakecoin" {$Divisor *= 1000}
        "decred" {$Divisor *= 1000}
        "equihash" {$Divisor /= 1000}
        "keccak" {$Divisor *= 1000}
        "quark" {$Divisor *= 1000}
        "qubit" {$Divisor *= 1000}
        "scrypt" {$Divisor *= 1000}
        "x11" {$Divisor *= 1000}

    }

    if ((Get-Stat -Name "$($Name)_$($Zpool_Algorithm_Norm)_Profit") -eq $null) {$Stat = Set-Stat -Name "$($Name)_$($Zpool_Algorithm_Norm)_Profit" -Value ([Double]$Zpool_Request.$_.estimate_last24h / $Divisor) -Duration (New-TimeSpan -Days 1)}
    else {$Stat = Set-Stat -Name "$($Name)_$($Zpool_Algorithm_Norm)_Profit" -Value ([Double]$Zpool_Request.$_.estimate_current / $Divisor) -Duration $StatSpan -ChangeDetection $true}

    $Zpool_Regions | ForEach-Object {
        $Zpool_Region = $_
        $Zpool_Region_Norm = Get-Region $Zpool_Region

        $Zpool_Currencies | ForEach-Object {
            [PSCustomObject]@{
                Algorithm     = $Zpool_Algorithm_Norm
                Info          = $Zpool_Coin
                Price         = $Stat.Live
                StablePrice   = $Stat.Week
                MarginOfError = $Stat.Week_Fluctuation
                Protocol      = "stratum+tcp"
                Host          = "$Zpool_Algorithm.$Zpool_Host"
                Port          = $Zpool_Port
                User          = Get-Variable $_ -ValueOnly
                Pass          = "$Worker,c=$_"
                Region        = $Zpool_Region_Norm
                SSL           = $false
                Updated       = $Stat.Updated
            }
        }
    }
}

**Comment by UselessGuru** [comment] 2018-03-05 19:46
@spartan5v5 

The posted file is not original and causes errors:

```
Missing property name after reference operator.

At C:\Users\Stephan\AppData\Local\Temp\3db1df3d-3bce-4d7a-9069-f817dd705ca5.ps1:32 char:176
+ ... me | Where-Object {$Zpool_Request.$.hashrate -gt 0} |ForEach-Object {
+                                                                         ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingPropertyName
```

[Re-download the original file](https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Pools/Zpool.ps1)

**Comment by spartan5v5** [comment] 2018-03-05 19:53
Im going to download all again and try, i have tried that file because it have divisors corrected but when i put in pools folder says "no pools" or something, with ahashpool occurs the same thing.

But im going to download all again and tell if works, its the best
Thanks.

**Comment by spartan5v5** [comment] 2018-03-06 06:32
Stop again with all new installed and that file says "No pools available"

**Comment by UselessGuru** [comment] 2018-03-06 07:23
> "No pools available" 

There clearly is a config error. What pools have youfigured. Have you manually removed files in the 'Pools' directory?

Please post the bat file you use to start MPM (rename to .txt and drag/drop). Also post config.txt.

**Comment by spartan5v5** [comment] 2018-03-06 07:27
its crypto-aliens... i removed all files from pools and leave zpool only.
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783885/Config.txt)
[Start.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1783886/Start.txt)

**Comment by UselessGuru** [comment] 2018-03-06 07:33
Do not remove files from the pools folder. [See the reason here](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1395)

**Comment by spartan5v5** [comment] 2018-03-06 07:34
But then change randomly if i want use only one pool.

**Comment by UselessGuru** [comment] 2018-03-06 07:44
Please [read this on how to configure the pools](https://github.com/MultiPoolMiner/MultiPoolMiner#command-line-options) to use.

**Comment by spartan5v5** [comment] 2018-03-06 08:06
-ExcludePoolName can be the solution?

**Comment by spartan5v5** [comment] 2018-03-06 08:13
Im going to try again, thank you.

**Comment by spartan5v5** [comment] 2018-03-06 11:01
All fresh install, no delete files, no new folder, reinstall nvidia drivers, cuda etc...  and occurs again.

I put the new ps1 pools files in pools folder and it give me "no pools"

**Comment by UselessGuru** [comment] 2018-03-06 11:30
> I put the new ps1 pools files in pools folder and it give me "no pools"

MPM needs to download the miner binaries first.
Can you see the 'Downloads' folder? Any files in there?
Did MPM already create a file structure in the 'Bin' folder?

**Comment by spartan5v5** [comment] 2018-03-06 12:42
In Bin folder there are the miners and in download the 7z.

**Comment by UselessGuru** [comment] 2018-03-06 13:07
Please post (drag and drop / no screenschots) start.bat and config.txt

**Comment by spartan5v5** [comment] 2018-03-06 13:09
[Config.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1785088/Config.txt)

[Start.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1785091/Start.txt)

**Comment by UselessGuru** [comment] 2018-03-06 13:23
Working fine here. This is what I did:

- I downloaded the [lastest zip file](url) and extract to new dir
- copied your config.txt and start.txt (renamed to start.bat)
- start 'start.bat'
-> MPM is downloading and unpacking miners
-> starts mining:

![untitled](https://user-images.githubusercontent.com/30080938/37034508-cbb55b74-2149-11e8-9a33-470a0b3f93d1.png)

**Comment by spartan5v5** [comment] 2018-03-06 13:25
Im doing all again................ deleted all and last try...

**Comment by spartan5v5** [comment] 2018-03-06 18:54
I did all again and stop mining again here...

![captura de pantalla 2018-03-06 a las 19 53 57](https://user-images.githubusercontent.com/37022773/37051961-27c54374-2178-11e8-921a-886d733bb62c.png)

**Comment by aaronsace** [comment] 2018-03-06 19:01
@spartan5v5 What are you showing in the screenshot?

**Comment by spartan5v5** [comment] 2018-03-06 19:03
Stop at this point or loading pool information.

**Comment by aaronsace** [comment] 2018-03-06 19:06
Says 19:48 on the last entry; how long did you wait to know it has stopped? (not sure what time zone you are in)

**Comment by spartan5v5** [comment] 2018-03-06 19:09
Im in Spain, is stopped because do nothing only that screen and in monitoring was red... when it happens sure is stopped, i restart and is working again but elapsed time stop again....

**Comment by aaronsace** [comment] 2018-03-06 19:10
Did you click on the screen because that pauses it?

**Comment by aaronsace** [comment] 2018-03-06 19:12
Have you got the frozen miner open now?

**Comment by spartan5v5** [comment] 2018-03-06 19:13
Now 3 rigs are working, I thought was OC and put it to 0 Overclock.

**Comment by spartan5v5** [comment] 2018-03-06 19:49
One stop again...

**Comment by aaronsace** [comment] 2018-03-06 20:33
@spartan5v5 That's why it just looks like you paused PowerShell...

**Comment by spartan5v5** [comment] 2018-03-06 21:33
I think found my issue, unchek this for not pause in powershell and cmd.

![captura de pantalla 2018-03-06 a las 22 11 48](https://user-images.githubusercontent.com/37022773/37059672-542531d4-218e-11e8-81e7-7a5874dd5b2d.png)

**Comment by UselessGuru** [comment] 2018-03-06 21:37
@spartan5v5 

Thank you for your feedback. This is a well known issue, e.g.: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/547

**Comment by spartan5v5** [comment] 2018-03-07 06:45
That dont work... all are stopped but still mining... the problem is that i dont know what is doing.

**Comment by UselessGuru** [comment] 2018-03-07 11:53
From https://github.com/MultiPoolMiner/MultiPoolMiner/issues/547

> When you hit the escape-button the window will continue.

???

**Comment by aaronsace** [comment] 2018-03-07 12:10
FYI, the monitor window and miner are two separate running PowerShell windows so you need to check both.

**Comment by spartan5v5** [comment] 2018-03-07 12:11
No, freeze like ice.

The two windows are unchecked.

**Comment by aaronsace** [comment] 2018-03-07 12:14
Can you post the log of each time it froze? Each time are they always at the same stage?

**Comment by spartan5v5** [comment] 2018-03-07 12:26
The 3 rigs are freeze in "loading pool information"

[Logs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1789105/Logs.zip)

**Comment by aaronsace** [comment] 2018-03-07 12:35
If you are sure it always freezes there then we need to look at any potential lines of codes that could cause it to hang forever between these two points: 

https://github.com/MultiPoolMiner/MultiPoolMiner/blob/7f1cb08406be5097f8c121d486b9537e1179bff0/MultiPoolMiner.ps1#L233-L267

**Comment by spartan5v5** [comment] 2018-03-07 13:27
Its strange, miner is writing logs... sure it sotopo here:

2018-03-07 04:52:59 INFO: Loading pool information. 
2018-03-07 04:53:02 INFO: Selecting best pool for each algorithm. 
2018-03-07 04:53:03 WARNING: Pool prices are out of sync (15 minutes). 
2018-03-07 04:53:03 INFO: Getting miner information. 
2018-03-07 04:53:09 INFO: Calculating profit for each miner. 
2018-03-07 04:53:13 INFO: Pinging monitoring server. 
2018-03-07 04:53:13 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
2018-03-07 04:53:13 INFO: Start waiting before next run. 
2018-03-07 04:54:03 INFO: Finish waiting before next run. 
2018-03-07 04:54:03 INFO: Saving hash rates. 
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:05][01;37m [S/A/T]: 0/2470/2470, diff: 0.113, 15.69MH/s [32myes![0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:07][01;37m [S/A/T]: 0/2471/2471, diff: 0.081, 15.68MH/s [32myes![0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:09][36m xevan block 204372, diff 276.055[0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:41][36m xevan block 204373, diff 276.037[0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:42][36m xevan block 204374, diff 273.000[0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:45][36m xevan block 204375, diff 272.765[0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:46][01;37m [S/A/T]: 0/2472/2472, diff: 0.118, 15.68MH/s [32myes![0m
2018-03-07 04:54:05 VERBOSE: CcminerXevan: [2018-03-07 04:53:53][36m xevan block 204376, diff 277.131[0m
2018-03-07 04:54:05 INFO: Starting next run. 
2018-03-07 04:54:05 INFO: Updating exchange rates from Coinbase. 
2018-03-07 04:54:05 INFO: Loading saved statistics. 
2018-03-07 04:54:07 INFO: Loading pool information

But i can see a new log at 13:24

[CcminerXevan-4068_2018-03-07_02-37-22.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1789266/CcminerXevan-4068_2018-03-07_02-37-22.txt)

**Comment by spartan5v5** [comment] 2018-03-07 13:54
I saw multipoolminer.ps1 and is the same posted... i think must be powershell issue.

**Comment by spartan5v5** [comment] 2018-03-08 06:44
I fixed it, must no delete files and use -ExcludePoolName and increase this to 256 or other value.

![captura de pantalla 2018-03-08 a las 7 43 52](https://user-images.githubusercontent.com/37022773/37137077-83d7cc4a-22a4-11e8-802f-cc5fe696af0f.png)

**Closed** 2018-03-15 22:20 UTC
